# Generated by Django 4.1.1 on 2022-09-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='birthday',
            field=models.CharField(db_column='birth', default='19001011', max_length=10, verbose_name='birth'),
        ),
    ]
